trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildconfiguration: 'Release'

steps:
  - task: UseDotNet@2
  - script: dotnet build --configuration $(buildConfiguration) 
    displayName: 'dotnet build $(buildConfiguration)'
  - task: DotNetCoreCLI@0
    displayName: dotnet test
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      testrunTitle: 'xUnit Test Run'